# Generated by Django 5.1.4 on 2024-12-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image_name",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(null=True, upload_to="posts"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="caption",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
